scopes:
  source:
    files:
      security:
        include:
          - never/**
      docs:
        include:
          - docs/**
  barrier_files:
    include:
      - .mergify.yml
pull_request_rules: []
